### PR TITLE
feat(DeviceControlGroup): add interview button

### PR DESCRIPTION
**Pull request by justfalter**
* Adds an "interview" button which starts an interview for the associated device. See https://github.com/Koenkk/zigbee2mqtt/pull/22788
* The icon is [fa-info](https://fontawesome.com/v6/icons/info?f=classic&s=solid).

### CODE REVIEW

**Comment by LaurentChardin** [comment]
@justfalter You just need to run prettier on your files to align the formatting.

**Comment by Koenkk** [comment]
@justfalter please run `npm run pretty` as @LaurentChardin indicated, then this is ready for merge.

**Comment by justfalter** [comment]
@LaurentChardin @Koenkk all prettied up!

**Comment by Koenkk** [comment]
Many thanks!

**Comment by Great-Chart** [comment]
Apologies if this isn't the best place to add this (minor) point; but it seems a logical place to include it.

I had one problem device that I'd need to re-pair occasionally and it would fail and interview and I can confirm this has resolved that (long standing issue)!  But when attempting this on a mobile device it's very hard to be sure that I'd actually clicked on Interview and not Reconfigure (the former icon being narrow thus the target box itself if narrower than most (worse on mobile).
image


As the dialogue box appears largely a duplicate of that for the Reconfigure option its worth noting that neither pop-ups actually define themselves as Reconfigure of Interview (Whereas those for Rename and Delete do include this).
With the Reconfigure and (new) Interview icons so close and them presenting identical pop-up dialogue boxes both named as Confirmation Prompt its not obvious which you are acknowledging!
image
But some appropriate text would (likely) make all the difference.
image


It would thus be useful if all such pop-up dialogue boxes adopted this additional clarity.

**Comment by NickVulkers** [comment]
> Apologies if this isn't the best place to add this (minor) point; but it seems a logical place to include it.
> 
> I had one problem device that I'd need to re-pair occasionally and it would fail and interview and I can confirm this has resolved that (long standing issue)! But when attempting this on a mobile device it's very hard to be sure that I'd actually clicked on Interview and not Reconfigure (the former icon being narrow thus the target box itself if narrower than most (worse on mobile). image
> 
> As the dialogue box appears largely a duplicate of that for the Reconfigure option its worth noting that neither pop-ups actually define themselves as Reconfigure of Interview (Whereas those for Rename and Delete do include this). With the Reconfigure and (new) Interview icons so close and them presenting identical pop-up dialogue boxes both named as Confirmation Prompt its not obvious which you are acknowledging! image But some appropriate text would (likely) make all the difference. image
> 
> It would thus be useful if all such pop-up dialogue boxes adopted this additional clarity.

+1, I've had to do this a few times recently and the target box sizing quickly became my enemy. Clarifying your requested action in the confirmation prompt is already a good step, even better would be reworking the buttons for mobile devices.

**Pull request merged**
