### PR TITLE
feat(gradient): support setting philips hue gradients

### PR DESCRIPTION
**Pull request by zegl**
Screenshot 2022-11-29 at 18 46 19

Updates https://github.com/Koenkk/zigbee2mqtt/issues/15243

### CODE REVIEW

**Comment by nurikk** [comment]
Hello, do you have exposes definition for this feature? It seems you’re adding new exposes type

**Comment by zegl** [comment]
Hey @nurikk! Yes, I've been working on new definitions over in https://github.com/Koenkk/zigbee-herdsman-converters/pull/5049. I realise that I might have opened this PR pre-maturely, but I wanted to work in the open as much as possible when adding this feature. Sorry about that!

I'll notify you and ask for your review if/when the PR to zigbee-herdsman-converters is merged.

**Comment by zegl** [comment]
Hey @nurikk, the feature has now been merged to zigbee-herdsman-converters. There was some API changes since the first version of this PR, and the changes in b954996 are reflecting the latest changes. 

Here is a quick demo of me using the UI:

https://user-images.githubusercontent.com/47952/206696919-e87f1ab2-832a-4624-99b4-4d57f99e89ef.mov

I'd appreciate any feedback that you might have, and it would be really cool to get this merged. Thanks!

**Comment by jb123567** [comment]
@zegl is this just waiting for approval or has this now been pushed. Will be great to actually have proper control in Z2M

**Comment by zegl** [comment]
@jb123567 It's waiting for review and approval from @nurikk.

**Comment by jb123567** [comment]
> @jb123567 It's waiting for review and approval from @nurikk. 

Excellent, I'll keep an eye. Thanks again for all your effort!

**Comment by nurikk-sa** [comment]
Brilliant job. Thanks for your contribution!

**Pull request merged**
