### PR TITLE
fix(expose): label not shown

### LINKED ISSUE #1792: [Bug]: Xiaomi DJT11LM not showing setting headers
### What happened?

Unsure what these settings are as there is no headers (in pink)
Screenshot 2023-10-04 at 7 18 17 am

I am guessing some are angle and sensitvity but not sure of the rest

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

_No response_

### Did you download state.json.zip?

I will not attach state.json.zip

### PR DESCRIPTION
**Pull request by Rotzbua**
Show label independent of additional description.
fixes #1792

### CODE REVIEW

**Comment by nurikk** [comment]
Wouldn’t it break existing implementations?

**Comment by Rotzbua** [comment]
@nurikk I will rebase and check.

**Comment by Rotzbua** [comment]
Sensor: Aqara vibration sensor

With my live system (koenkk/zigbee2mqtt:1.33.0):

grafik

With the test data provided by the repository:
grafik

Maybe the test data outdated?

**Comment by nurikk** [comment]
> Sensor: Aqara vibration sensor
> 
> With my live system (koenkk/zigbee2mqtt:1.33.0):
> 
> grafik
> 
> With the test data provided by the repository: grafik
> 
> Maybe the test data outdated?

Yes, test data is outdated

**Pull request merged**
