### PR TITLE
Update chs.json

### PR DESCRIPTION
**Pull request by FaintGhost**
just add more translations

### CODE REVIEW

**Comment by nurikk** [comment]
Hi, thank you! But I don't accept translation pull requests from github. Kindly join our translation project here https://poeditor.com/projects/view?id=494809, you can continue helping with localisation there

**Comment by FaintGhost** [comment]
> Hi, thank you! But I don't accept translation pull requests from github. Kindly join our translation project here [poeditor.com/projects/view?id=494809](https://poeditor.com/projects/view?id=494809), you can continue helping with localisation there

I will join this translation project, but the url you sent me returned an error page.

**Comment by nurikk** [comment]
> > Hi, thank you! But I don't accept translation pull requests from github. Kindly join our translation project here [poeditor.com/projects/view?id=494809](https://poeditor.com/projects/view?id=494809), you can continue helping with localisation there
> 
> I will join this translation project, but the url you sent me returned an error page.

sorry, my bad. this is correct url https://poeditor.com/join/project?hash=Az88waAhPd

**Comment by FaintGhost** [comment]
Got it! I'll close this pull request.

**Pull request closed without merging**
