### PR TITLE
2 minutes is rather optimistic, let's make it 5

### PR DESCRIPTION
**Pull request by wolph**
The 2 minutes maximum is a bit optimistic, perhaps I just have an unusually large or complex zigbee network but it's taking well over 4 minutes for me.

### CODE REVIEW

**Comment by ReneTode** [comment]
even 5 is optimistic.
it takes up to 15 minutes for me.

**Comment by jhanninen** [comment]
How about less precise time definition, if it happens to vary a lot?

For example:
> Depending on the size of your network this can take several minutes.

**Comment by ReneTode** [comment]
or something like:

> we cant say how long it takes, it can be a few seconds or more then 30 minutes.

**Comment by wolph** [comment]
I've updated it to say between 10 seconds and 30 minutes. It's good to have some number I suppose :)

**Comment by wolph** [comment]
This really shouldn't have been closed... stupid stale bot :P

**Pull request closed without merging**
