### PR TITLE
small layout change on device-page

### PR DESCRIPTION
**Pull request by timoline**
small layout change on device-page

### CODE REVIEW

**Comment by nurikk** [comment]
What are this changes for?

**Comment by timoline** [comment]
> What are this changes for?
just some ui changes

image

**Comment by nurikk** [comment]
it messes up with mobile view
Screenshot 2020-12-31 at 17 19 56

**Comment by timoline** [comment]
Don't see that problem over here...
And I didnt change anything on the navbar section

**Comment by nurikk** [comment]
It's CSS man😁

**Comment by timoline** [comment]
> It's CSS man😁

CSS mess

**Comment by timoline** [comment]
> > It's CSS man😁
> 
> CSS mess

And now?
I think I'm not going to fix this, since I cant reproduce it...

**Pull request closed without merging**
