### PR TITLE
fix(): exposed enums with numeric values are not showing the selected value

### LINKED ISSUE #1466: [Bug]: exposed enums with numeric values are not showing the selected value
### What happened?

ZM-35H-Q is exposing the enum "keep_time". The enum values are strings, but the value in the state is numeric. This is causing the UI to not show the selected value.
image
image

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

_No response_

### Did you download state.json.zip?

I will not attach state.json.zip

### PR DESCRIPTION
**Pull request by regevbr**
fix #1466

I enabled type coercion in the value comparison to fix the issue. I validated the fix using the dev device at http://localhost:3030/#/device/0x00158d000566bde7/exposes

image

### CODE REVIEW

**Comment by nurikk** [comment]
let's fix enum in the first place, non need to introduce value coercion as a workaround

**Comment by regevbr** [comment]
> let's fix enum in the first place, non need to introduce value coercion as a workaround

sure, thought that this will keep backward compatibility... Also you can see that the second comparison done in the same line is also just `==` so we need to decide here what kind of comparison we should do in both of them. Thoughts?

**Comment by nurikk** [comment]
> > let's fix enum in the first place, non need to introduce value coercion as a workaround
> 
> sure, thought that this will keep backward compatibility... Also you can see that the second comparison done in the same line is also just `==` so we need to decide here what kind of comparison we should do in both of them. Thoughts?

it should be `===`, thanks for pointing out

**Comment by regevbr** [comment]
> > > let's fix enum in the first place, non need to introduce value coercion as a workaround
> > 
> > 
> > sure, thought that this will keep backward compatibility... Also you can see that the second comparison done in the same line is also just `==` so we need to decide here what kind of comparison we should do in both of them. Thoughts?
> 
> it should be `===`, thanks for pointing out

cool, I see you already fixed it :-)

**Pull request closed without merging**
