### PR TITLE
Hungarian language settings + request for Poeditor settings

### PR DESCRIPTION
**Pull request by v1k70rk4**
Based on a previous description, I have set up the Hungarian language and created a base hu.json file to avoid any issues. And I would like to have the Hungarian language set up on Poeditor as well. Thank you in advance.

### CODE REVIEW

**Comment by Koenkk** [comment]
@nurikk how are new languages added? Do they need to be added to https://poeditor.com/join/project?hash=Az88waAhPd first?

**Comment by v1k70rk4** [comment]
Hello,

Is there a reason why Hungarian is not being added? Is there something wrong with the request? Can I possibly improve something?

Viktor

**Comment by Koenkk** [comment]
@nurikk can I merge this?

**Comment by nurikk** [comment]
I've added Hungarian locale in Poeditor, please use it to make your changes. I'll add new locale after it has enough translations

**Comment by v1k70rk4** [comment]
Hello, thank you both. Well, I've also started the translation. I'm not working this week because I caught a cold, so it's going quickly.
I've started working on translating "featureNames" with great effort :), and "featureDescriptions" will be the last. The other categories are done, I'm currently at around 41%. 
I'm not sure how much you've thought about consolidation, but I think it can already be a big help for Hungarians :)

Thank you for your work so far. Practically 90% of my devices are Zigbee and they work flawlessly. :)

**Comment by nurikk** [comment]
> Hello, thank you both. Well, I've also started the translation. I'm not working this week because I caught a cold, so it's going quickly. I've started working on translating "featureNames" with great effort :), and "featureDescriptions" will be the last. The other categories are done, I'm currently at around 41%. I'm not sure how much you've thought about consolidation, but I think it can already be a big help for Hungarians :)
> 
> Thank you for your work so far. Practically 90% of my devices are Zigbee and they work flawlessly. :)

Get well mate! I’ve also fell sick to cold. But don’t worry, I’ll include your work before next release

**Comment by nurikk** [comment]
omg guys! 100% translation in less than a month! you're guys crazy! :)

**Comment by v1k70rk4** [comment]
I had quite a bit of free time :) But this was also translated and I have recovered.

I'm glad I'll see it, because in English there is often one word for many things, while in Hungarian there is a separate word for everything :) and the context also matters. Therefore, it was necessary to cherry-pick from several source languages. Thankfully, Germans are usually precise and they also have a word for everything, so I hope it turned out well, but I'll still refine it.

Fun fact: we have more than 10 words for a bicycle :D

**Comment by v1k70rk4** [comment]
Hello, just one question. Hungarian language has been added, but it seems like there are some parts still in English, and apparently the strings appear on the POE editor.

I cleared the cache and tried everything. Is this good?

PS:
Oops, I checked and it's the same with other 100% complete languages too.
image

**Pull request merged**
